name: 🚀 Build and Deploy to CPanel
on:
  push:
    branches:
      - 'main'
      - '10-setup-continuous-deployment-to-cpanel-using-github-actions'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Nodejs version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install yarn dependencies
        run: yarn

      - name: Build Project
        run: yarn build
        env:
          CI: false

      - name: List built files
        run: find build/ -print 